checks:
    python:
        code_rating: true
        duplicate_code: true
filter:
    paths: ['*']
build:
    environment:
        python: 3.6.0
        postgresql: false
        redis: false
        docker:
            remote_engine: true
            cache:
                images:
                    - kytos/nightly
    dependencies:
        before:
            - pip install coverage git+git://github.com/diraol/watchdog.git#egg=watchdog
            - sudo apt install -y mininet

    tests:
        override:
            - /usr/bin/python tests/integration/hooks/pre/mn_topo13.py
            - py-scrutinizer-run
